package menu;




import Postacie.PostacArcher;
import Gra.Bohaterowie.*;
import Gra.Potwory.miniBoss;
import bosy.miniBosArcher;
import javax.swing.JOptionPane;
import walkaArcher.WybórPotworaA;
import static Gra.Potwory.Potwory.*;
import static WalkaLvl5Archer.Powyzej5potwory.*;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import Zapis.ZapisIOdczyt.*;
import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marci
 */
public class MenuArcher extends javax.swing.JFrame {

        public static Archer archer = new Archer();
        public static Archer archerhp = new Archer();
        public static miniBoss miniboss = new miniBoss(3400, 100);
    public static miniBoss minibosshp = new miniBoss(3400, 100);
        public static miniBoss miniboss1 = new miniBoss(3400, 100);
    public static miniBoss minibosshp1 = new miniBoss(3400, 100);
        public static miniBoss boss = new miniBoss(10000, 500);
    public static miniBoss bosshp = new miniBoss(10000, 500);

    public MenuArcher() {
        initComponents();
        this.setLocationRelativeTo(null);
        jama.setEnabled(false);
        if(archer.hpbohater<=0)
        {
            walcz.setEnabled(false);
        }
        if(archer.lvl>=10)
        {
            jama.setEnabled(true);
        }
                  if(archer.hpbohater<=0&&archer.hajs<50)
            {
                int a =JOptionPane.showConfirmDialog(null, "Nie masz życia i nie masz pieniędzy na bandaż... "
                +"\n Czy chcesz zacząć od nowa ? ");
                if(a==0)
                    this.dispose();
                new Logowanie.Logowanie().setVisible(true);
                    
            }
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intro = new javax.swing.JLabel();
        postac = new javax.swing.JButton();
        sklep = new javax.swing.JButton();
        walcz = new javax.swing.JButton();
        wyjdz = new javax.swing.JButton();
        grafika = new javax.swing.JLabel();
        jama = new javax.swing.JButton();
        Zapisz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("For The Exp");

        intro.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        intro.setText("For The Exp");

        postac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/obrazki menumag/head.png"))); // NOI18N
        postac.setText("Postać");
        postac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postacActionPerformed(evt);
            }
        });

        sklep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/obrazki menumag/money1.gif"))); // NOI18N
        sklep.setText("Sklep");
        sklep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sklepActionPerformed(evt);
            }
        });

        walcz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/obrazki menumag/fight.png"))); // NOI18N
        walcz.setText("Walcz");
        walcz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walczActionPerformed(evt);
            }
        });

        wyjdz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/obrazki menumag/exit.gif"))); // NOI18N
        wyjdz.setText("Wyjdz");
        wyjdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzActionPerformed(evt);
            }
        });

        grafika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/obrazki menumag/barrow.gif"))); // NOI18N

        jama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/obrazki menumag/dragon.png"))); // NOI18N
        jama.setText("Jama ");
        jama.setToolTipText("Dostępna od 10 LVL");
        jama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamaActionPerformed(evt);
            }
        });

        Zapisz.setText("Zapisz");
        Zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapiszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wyjdz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(walcz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(postac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sklep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Zapisz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(grafika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(postac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sklep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(walcz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wyjdz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Zapisz)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(grafika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postacActionPerformed
            new PostacArcher().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_postacActionPerformed

    private void walczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walczActionPerformed

        new WybórPotworaA().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_walczActionPerformed

    private void sklepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sklepActionPerformed
        new SklepArcher().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sklepActionPerformed

    private void wyjdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzActionPerformed
                int a = JOptionPane.showConfirmDialog(null, "Czy napewno chcesz wyjść z gry ? ");
        if(a==0)
        this.dispose();
    }//GEN-LAST:event_wyjdzActionPerformed

    private void jamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamaActionPerformed
        new miniBosArcher().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jamaActionPerformed

    private void ZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapiszActionPerformed
       int a= JOptionPane.showConfirmDialog(null, "Czy Napewno chcesz zapisać aktualny stan gry, tej operacji nieda się cofnąć? ");
if(a==0){
        try {
                PrintWriter zapis = new PrintWriter("MenuArcher.txt");
                PrintWriter zapisPotworyArcher = new PrintWriter("MenuArcherPotwory.txt");
                
                Zapis.ZapisIOdczyt.zapisz(archer,archerhp, zapis);
                Zapis.ZapisIOdczyt.zapiszPotwor(golum, golumhp,zombie, zombiehp,szkielet,szkielethp,wilk, wilkhp,smok, smokhp,skorpion, skorpionhp, zapisPotworyArcher);
                


                
            } catch (FileNotFoundException ex) {
                ex.getMessage();
            }
}
else
{
    
}
    }//GEN-LAST:event_ZapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuArcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuArcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuArcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuArcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuArcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Zapisz;
    private javax.swing.JLabel grafika;
    private javax.swing.JLabel intro;
    private javax.swing.JButton jama;
    private javax.swing.JButton postac;
    private javax.swing.JButton sklep;
    private javax.swing.JButton walcz;
    private javax.swing.JButton wyjdz;
    // End of variables declaration//GEN-END:variables
}
