/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logowanie;

import static Gra.Potwory.Potwory.golum;
import static Gra.Potwory.Potwory.golumhp;
import static Gra.Potwory.Potwory.szkielet;
import static Gra.Potwory.Potwory.szkielethp;
import static Gra.Potwory.Potwory.zombie;
import static Gra.Potwory.Potwory.zombiehp;
import Intro.Intro;
import static WalkaLvl5Archer.Powyzej5potwory.skorpion;
import static WalkaLvl5Archer.Powyzej5potwory.skorpionhp;
import static WalkaLvl5Archer.Powyzej5potwory.smok;
import static WalkaLvl5Archer.Powyzej5potwory.smokhp;
import static WalkaLvl5Archer.Powyzej5potwory.wilk;
import static WalkaLvl5Archer.Powyzej5potwory.wilkhp;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import menu.MenuArcher;
import static menu.MenuArcher.archer;
import static menu.MenuArcher.archerhp;
import menu.MenuMag;
import static menu.MenuMag.mag;
import static menu.MenuMag.maghp;
import menu.MenuPaladyn;
import static menu.MenuPaladyn.paladyn;
import static menu.MenuPaladyn.paladynhp;

/**
 *
 * @author marci
 */
public class Wczytywanie extends javax.swing.JFrame {

    /**
     * Creates new form Wczytywanie
     */
    public Wczytywanie() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Paladyn = new javax.swing.JButton();
        Mag = new javax.swing.JButton();
        Archer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Wybierz Zapis i Postać do której jest on przypisany ");

        Paladyn.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        Paladyn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logowanie/kursor.gif"))); // NOI18N
        Paladyn.setText("Paladyn");
        Paladyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaladynActionPerformed(evt);
            }
        });

        Mag.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        Mag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logowanie/book.png"))); // NOI18N
        Mag.setText("Mag");
        Mag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagActionPerformed(evt);
            }
        });

        Archer.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        Archer.setIcon(new javax.swing.ImageIcon("C:\\Users\\marci\\Documents\\NetBeansProjects\\Gra\\src\\Logowanie\\bow.gif")); // NOI18N
        Archer.setText("Archer");
        Archer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArcherActionPerformed(evt);
            }
        });

        jButton1.setText("Wróć");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Paladyn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Archer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mag, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(Paladyn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Archer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaladynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaladynActionPerformed
  File czytacz = new File("MenuPaladyn.txt");
  File czytaczPal2 = new File("MenuPaladynPotwory.txt");
                    if(czytacz.exists()==false)
                    {
                        JOptionPane.showMessageDialog(null, "Zapis dla tej postaci nie istnieję, wróć i zacznij od nowa");
                        
                    }
                    else
                    {
                    
        int a = JOptionPane.showConfirmDialog(null, "Postać którą chcesz wczytać to Paladyn, jesteś pewien? ");
        if(a==0){
            new MenuPaladyn().setVisible(true);
            
            
                        
                  
            try {
                Zapis.ZapisIOdczyt.odczytaj(paladyn,paladynhp, czytacz);
                                                Zapis.ZapisIOdczyt.odczytajPotwor(golum, golumhp,zombie, zombiehp,szkielet,szkielethp,wilk, wilkhp,smok, smokhp,skorpion, skorpionhp, czytaczPal2);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuArcher.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.dispose();
        }
        else
        {

        }
                    }
    }//GEN-LAST:event_PaladynActionPerformed

    private void MagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagActionPerformed
File czytaczmag = new File("MenuMag.txt");
File czytaczmag2 = new File("MenuMagPotwory.txt");
        if(czytaczmag.exists()==false)
                    {
                        JOptionPane.showMessageDialog(null, "Zapis dla tej postaci nie istnieję, wróć i zacznij od nowa");
                        
                    }
        else
        {
        int a = JOptionPane.showConfirmDialog(null, "Postać którą chcesz wczytać to Mag, jesteś pewien? ");
        if(a==0){
            new MenuMag().setVisible(true);
            
                        
                    
            try {
                Zapis.ZapisIOdczyt.odczytaj(mag,maghp, czytaczmag);
                                                Zapis.ZapisIOdczyt.odczytajPotwor(golum, golumhp,zombie, zombiehp,szkielet,szkielethp,wilk, wilkhp,smok, smokhp,skorpion, skorpionhp, czytaczmag2);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuArcher.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        else
        {

        }}
    }//GEN-LAST:event_MagActionPerformed

    private void ArcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArcherActionPerformed
File czytacz = new File("MenuArcher.txt");
File czytacz2 = new File("MenuArcherPotwory.txt");
        if(czytacz.exists()==false)
                    {
                        JOptionPane.showMessageDialog(null, "Zapis dla tej postaci nie istnieję, wróć i zacznij od nowa");
                        
                    }
        else
        {
        int a = JOptionPane.showConfirmDialog(null, "Postać którą chcesz wczytać to Archer, jesteś pewien? ");
        if(a==0){
            new MenuArcher().setVisible(true);
                   
            try {
                Zapis.ZapisIOdczyt.odczytaj(archer,archerhp, czytacz);
                                Zapis.ZapisIOdczyt.odczytajPotwor(golum, golumhp,zombie, zombiehp,szkielet,szkielethp,wilk, wilkhp,smok, smokhp,skorpion, skorpionhp, czytacz2);

            } catch (FileNotFoundException ex) {
                ex.getMessage();
            }
            this.dispose();
        }
        else
        {

        }}
    }//GEN-LAST:event_ArcherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Intro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wczytywanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wczytywanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wczytywanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wczytywanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wczytywanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Archer;
    private javax.swing.JButton Mag;
    private javax.swing.JButton Paladyn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
